Homework-6/SparkAuthors/config/routes.rb
Rails.application.routes.draw do
  root('home#index')
  resources :users
  resources :ebooks
  resources :orders
end

Homework-6/SparkAuthors/app/models/ebook.rb
class Ebook < ActiveRecord::Base
  has_and_belongs_to_many :user # foreign key - user_id
end

Homework-6/SparkAuthors/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user # foreign key - user_id
end

Homework-6/SparkAuthors/app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :ebooks
  has_many :orders
end

Homework-6/SparkAuthors/app/controllers/ebooks_controller.rb
class EbooksController < ApplicationController
  def index
    @ebooks = Ebook.all
  end
  def new
    @ebook = Ebook.new
  end
  def create
    @ebook = Ebook.create(ebook_params)
    redirect_to ebook_path(@ebook)
  end
  def show
    @user = User.find_by_id(:id)
    @ebook = Ebook.find_by_id(params[:id])
  end
  # This will render the edit form with pre-populated data.
  def edit
    @ebook = Ebook.find_by_id(params[:id])
  end
  # This updates and redirect when you hit submit to the show page for the user.
  def update
    # extract the **id** from the params object and use ActiveRecord to find the resource by its **id**.
    @ebook = Ebook.find_by_id(params[:id])
    # use ActiveRecord's update method save your updates.
    @ebook.update(ebook_params)
     # redirect to the show page of the updated character after the updates have been saved
     # since the show action (character_path maps to the show action) requires an id we can pass the enter Character instance as a parameter to the named route
    redirect_to ebook_path(@ebook) #this will redirect them to the user show page.
  end
  def destroy
     # extract the **id** from the params object and use ActiveRecord to find the resource by its **id**
    @ebook = Ebook.find(params[:id])
     # use ActiveRecord's destroy method to delete the resource
    @ebook.destroy
    # redirect to the index action (list view)
    redirect_to ebooks_path
  end

  private

  # This is a security measure that allows the fields in the new form to be permitted into the database.
  def ebook_params
    params.require(:ebook).permit(:title, :short_desc, :body, :genre, :cost)
  end
end

Homework-6/SparkAuthors/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Homework-6/SparkAuthors/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  #code
end

Homework-6/SparkAuthors/app/controllers/users_controller.rb
class UsersController < ApplicationController

  # This index method has an instance var that you used on your veiws page to display all the users records in the index veiw page.
  def index
    @users = User.all
  end
  # This will allow you to call the recorded information in the database for a given tabele.
  def show
    @user = User.find_by_id(params[:id])
  end
  # This action renders the form for users to sign up and create a record in the users table
  def new
    @user = User.new
  end
  # This will create a new user when you save the form and redirects to the show action.
  def create
    @user = User.create(user_params)
    redirect_to user_path(@user) #this will redirect them to the show page for that user.
  end
  # This will render the edit form with pre-populated data.
  def edit
    @user = User.find_by_id(params[:id])
  end
  # This updates and redirect when you hit submit to the show page for the user.
  def update
    # extract the **id** from the params object and use ActiveRecord to find the resource by its **id**.
    @user = User.find_by_id(params[:id])
    # use ActiveRecord's update method save your updates.
    @user.update(user_params)
     # redirect to the show page of the updated character after the updates have been saved
     # since the show action (character_path maps to the show action) requires an id we can pass the enter Character instance as a parameter to the named route
    redirect_to user_path(@user) #this will redirect them to the user show page.
  end
  def destroy
     # extract the **id** from the params object and use ActiveRecord to find the resource by its **id**
    @user = User.find(params[:id])
     # use ActiveRecord's destroy method to delete the resource
    @user.destroy
    # redirect to the index action (list view)
    redirect_to users_path
  end


  private
  # This is a security measure that allows the fields in the new form to be permitted into the database.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :gender, :age)
  end

end

Homework-6/SparkAuthors/app/views/ebooks/edit.html.erb
<h1>Edit eBook</h1>

<!-- This form will allow users to create ebooks in the database! -->
<%= form_for @ebook, url: {action: :update} do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </p>
  <p>
    <%= f.label :short_desc %><br>
    <%= f.text_area :short_desc %>
  </p>
  <p>
    <!-- your naming this story right now because you dont want to put text/body, but ultimately you want to enter a chapter dropdown. -->
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </p>


  <p>
    <%= f.submit%>
  </p>
<% end %>

Homework-6/SparkAuthors/app/views/ebooks/index.html.erb
<h1>Ebooks Index</h1>

<!-- create a loop that shows all the ebooks in the sys. -->
<%= @ebooks.each do |ebook| %>
  <p>
    <span><%= link_to ebook.title, ebook_path(ebook)%></span>
    <span><%= ebook.genre %></span>
    <span><%= ebook.short_desc%></span>
    <span><%= ebook.body %></span>
    <span><%= ebook.cost %></span>
  </p>

<% end %>

Homework-6/SparkAuthors/app/views/ebooks/new.html.erb
<h1>New Story</h1>


<!-- This form will allow users to create ebooks in the database! -->
<%= form_for @ebook, url: {action: :create} do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </p>
  <p>
    <%= f.label :short_desc %><br>
    <%= f.text_area :short_desc %>
  </p>
  <p>
    <!-- your naming this story right now because you dont want to put text/body, but ultimately you want to enter a chapter dropdown. -->
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </p>


  <p>
    <%= f.submit%>
  </p>
<% end %>

Homework-6/SparkAuthors/app/views/ebooks/show.html.erb
<h1>Show Ebook Detail</h1>


<% if @ebook %>
    <h1><%= @ebook.title %></h1>
    <h3><%= @ebook.short_desc %> </h3>
    <p><%= @ebook.body %> </p>
<% else %>
    <p>ebook not found!</p>
<% end %>

<!-- Sends users to the edit page for that specific user. -->
<%= link_to 'Edit', edit_ebook_path %> |
<!-- Send DELETE request to /characters/:id and add a confirmation box -->
<td><%= link_to 'Delete', ebook_path(@ebook), method: :delete, data: { confirm: 'Are you sure?' } %></td>

Homework-6/SparkAuthors/app/views/users/edit.html.erb
<h1>Edit User</h1>

<!-- create a link that lets users go back to the index view -->
<p><%= link_to 'Home page', users_path %></p>

<!-- the show should direct them to their user profile. -->
<%= form_for @user, url: {action: :update} do |f| %>
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :emial %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </p>
  <p>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </p>

  <p>
    <%= f.submit :submit %>
  </p>
<% end %>

Homework-6/SparkAuthors/app/views/users/index.html.erb
<h1>User Index</h1>


<!-- List all the users currently on the site.-->
<% @users.each do |user|%>
  <p>
    <span> <%=link_to user.first_name, user_path(user)%> </span>
    <span> <%= user.last_name%> </span>
    <span> <%= user.gender%> </span>
    <span> <%= user.email%> </span>
    <span> <%= user.age%> </span>
  </p>
<% end %>

Homework-6/SparkAuthors/app/views/users/new.html.erb
<h1>New Users</h1>

<!-- Create a users sign up form! -->
<%= form_for @user, url: {action: :create} do |f| %>
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :emial %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </p>
  <p>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </p>

  <p>
    <%= f.submit :submit %>
  </p>
<% end %>

Homework-6/SparkAuthors/app/views/users/show.html.erb
<h1>Show User</h1>

<% if @user %>
    <h1>Hello <%= @user.first_name %> <%= @user.last_name %> </h1>

    <p>You are a <%= @user.gender%> that's <%= @user.age %> years old.</p>
<% else %>
    <p>Character not found!</p>
<% end %>

<!-- Sends users to the edit page for that specific user. -->
<%= link_to 'Edit User', edit_user_path %> |
<!-- Send DELETE request to /characters/:id and add a confirmation box -->
<td><%= link_to 'Delete', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %></td>