Final Project/StockTracker/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  # restricting these because the devise user handles these
  resources :user_stocks, except: [:show, :edit, :update]
  resources :users, only: [:show]
  resources :friendships
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
end

Final Project/StockTracker/app/models/stock.rb
class Stock < ActiveRecord::Base

  has_many :user_stocks
  has_many :users, through: :user_stocks


  # We are adding the self. prior to the method name, because these methods are not tied to any objects or object lifecycle, we need to be able to use them without having any instances of a stock.

  # Your looking for an existing ticker_symbol, where the ticker: key is givent the ticker symbol argument first.
  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  # def a var tha let you look for a stock symbol that DOES NOT EXIST in the database. Then assign a var to the newly looked up stock quote (ticker_symbol) and gives it a new_stock price based on the last_price. It returns niil unless a stock name is found.
  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    return nil unless looked_up_stock.name

    # assingin a new_stock var to new instance where the ticker: key is given the looked_up_stock.symbol, and the name:key is is given the looked_up_stock.name.
    new_stock = new(ticker: looked_up_stock.symbol, name: looked_up_stock.name)

    # Calling the new looked_up_stock's last_price method and assinging it a new_stock.price method
    new_stock.last_price = new_stock.price

    # calling the new stock var which should be the newly assinged price for the looked_up_stockthat wsas that wasnt in the system.
    new_stock
  end

  #  Def a method that creates a price. closing_price and opening_price.
  def price
    # Creating a var that looks up closing_price by calling the close method for a looked up stock ticker. Then returns the closing_price with the word "Closing" if the closing_price is not nil.
    closing_price = StockQuote::Stock.quote(ticker).close
    return "#{closing_price} (Closing)" if closing_price

    # Creating a var that looks up the opening_price by calling the opening method for a looked up stock ticker. Then returns the opening_price with the word "Opening" if the opening_price is not nil.
    opening_price = StockQuote::Stock.quote(ticker).open
    return "#{opening_price} (Opening)" if opening_price

    # Return "Unavalable if the stock is ticker price is nil."
    'Unavailable'
  end
end

Final Project/StockTracker/app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  # Defining a search method/action that lets the user search. Then uses their params[:stock] if valid to find Stock.find_by_ticker orcreat a new_from_lookup params[:stock].
  def search
    if params[:stock]
      @stock = Stock.find_by_ticker(params[:stock])
      @stock ||= Stock.new_from_lookup(params[:stock])
    end

    # if you have any of the two @stock instance variable render the partial form Lookup.
    if @stock
      # render json: @stock
      render partial: 'lookup'
    # or else if not, render the status not found method.
    elsif true
      render status: :not_found, nothing: true
    end
  end
end

Final Project/StockTracker/app/views/stocks/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <% if @user.id == current_user.id %>
      <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user_stocks.each do |user_stock| %>
    <tr>
      <td><%= user_stock.name %></td>
      <td><%= user_stock.ticker %></td>
      <td><%= user_stock.price %></td>
      <% if @user.id == current_user.id %>
      <td>
        <%= link_to 'Delete', user_stock_path(user_stock),
                                :method => :delete,
                                :data => { :confirm => "Are you sure?"},
                                :class => "btn btn-xs btn-danger" %>
      </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

Final Project/StockTracker/app/views/stocks/_lookup.html.erb
<!-- Creating a form to render looking up stocks -->
<div id="stock-lookup">
  <h3>Search for Stocks</h3>
  <!-- This line of code calls the ajax javascript that submits the data notice the id you set! -->
  <%= form_tag search_stocks_path, remote: true, method: :get, id:   'stock-lookup-form' do %>
  <div class = "form-group row no-padding text-center col-md-12">
    <div class="col-md-10">
      <!-- this line of code is the actual search field thats entered by the users(params) and linked to the stock model. -->
      <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true,
                                                          class: 'form-control search-box input-lg' %>
    </div>
    <div class="col-md-2">
      <!-- Created a button to submit the search inquiry. -->
      <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
        <i class= "fa fa-search"></i> Look up a stock
      <% end %>
    </div>
  </div>
  <% end %>
  <!-- A Spinner that calls the spinner partial after looked_up_a_stock button is pressed -->
  <%= render 'common/spinner' %>

  <!-- if a stock is found, stock info would show -->
  <% if @stock %>
    <div id="stock-lookup-results" class="well results-block">
      <strong>Symbol:</strong> <%= @stock.ticker %>
      <strong>Name:</strong> <%= @stock.name %>
      <strong>Price:</strong> <%= @stock.price %>
      <!--  If the current user can add stocks? (set in method i user.rb model) show the link. -->
      <% if current_user.can_add_stock?(@stock.ticker) %>
        <%= link_to "Add to my Stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker,stock_id: @stock.id ? @stock.id : ''), class: 'btn btn-xs btn-success', method: :post %>
      <% else %>
        <span class='label label-default'>
          Stock cannot be added because you have already added
          <% if !current_user.under_stock_limit? %>
          10 stocks
          <% end %>
          <% if current_user.stock_already_added?(@stock.ticker) %>
          this stock
          <% end %>
        </span>
      <% end %>
    </div>
  <% end %>
  <div id="stock-lookup-errors">
  </div>
</div>